services:
  - type: web
    name: ansas-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0